#FastAPI app routes
from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from app.database import init_db
from app.engine import ingest_document, query_rag_pipeline

# 1. Define the Lifespan Context Manager
@asynccontextmanager
async def lifespan(app: FastAPI):
    """Handles application startup and shutdown lifecycle events."""
    print("Booting up backend server infrastructure...")
    init_db()  # Automatically verify or create the Qdrant vector collection
    yield      # The application runs and handles requests here
    print("Shutting down backend server infrastructure...")

# 2. Instantiate the Core FastAPI Application
app = FastAPI(
    title="Local Production RAG API",
    description="A secure, dependency-free local AI engineering pipeline.",
    version="1.0.0",
    lifespan=lifespan
)

# 3. Define Strict Pydantic Validation Schemas
class IngestRequest(BaseModel):
    doc_id: int = Field(..., description="Unique integer identifier for the document payload.")
    text: str = Field(..., min_length=1, description="The raw document text content to be vectorized.")

class QueryRequest(BaseModel):
    question: str = Field(..., min_length=1, description="The user question to process through the RAG pipeline.")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="The context-bounded output generated by the local LLM.")

# 4. Implement Web Endpoints
@app.post("/ingest", status_code=201)
async def endpoint_ingest_document(payload: IngestRequest):
    """Receives corporate data, vectorizes it, and commits it to the database."""
    try:
        ingest_document(doc_id=payload.doc_id, text=payload.text)
        return {"status": "success", "message": f"Document {payload.doc_id} successfully vectorized and indexed."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Database ingestion failed: {str(e)}")

@app.post("/query", response_model=QueryResponse)
async def endpoint_query_rag(payload: QueryRequest):
    """Executes vector similarity search and returns a strict, context-bounded answer."""
    try:
        ai_response = query_rag_pipeline(user_query=payload.question)
        return QueryResponse(answer=ai_response)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Pipeline execution failed: {str(e)}")